config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :projects do
  resources :sprints, :shallow => true do
    member do
      get :edit_effort
      put :update_effort
      get :burndown
      get :burndown_graph
    end
    collection do
      get :burndown_index
    end
  end
  post "sprints/change_task_status",
       :controller => :sprints, :action => :change_task_status,
       :as => :sprints_change_task_status

  resources :product_backlog, :shallow => true, :only => [:index] do
    collection do
      post :sort
      post :create_pbi
      get :burndown
      get :burndown_graph
    end
  end
  get "product_backlog/new_pbi/:tracker_id",
      controller: :product_backlog, action: :new_pbi,
      as: :product_backlog_new_pbi

end

post "issues/:id/story_points",
     :controller => :scrum, :action => :change_story_points,
     :as => :change_story_points
post "issues/:id/pending_effort",
     :controller => :scrum, :action => :change_pending_effort,
     :as => :change_pending_effort
post "issues/:id/assigned_to",
     :controller => :scrum, :action => :change_assigned_to,
     :as => :change_assigned_to
post "issues/:id/create_time_entry",
     :controller => :scrum, :action => :create_time_entry,
     :as => :create_time_entry
get "scrum/:sprint_id/new_pbi/:tracker_id",
     controller: :scrum, action: :new_pbi,
     as: :new_pbi
post "scrum/:sprint_id/create_pbi",
     controller: :scrum, action: :create_pbi,
     as: :create_pbi

app/models/sprint.rb
class Sprint < ActiveRecord::Base

  belongs_to :user
  belongs_to :project
  has_many :issues, :dependent => :destroy
  has_many :efforts, :class_name => "SprintEffort", :dependent => :destroy

  validates_presence_of :name
  validates_uniqueness_of :name, :scope => [:project_id]
  validates_length_of :name, :maximum => 60
  validates_presence_of :name

  validates_presence_of :start_date

  validates_presence_of :end_date
  
  before_destroy :update_project_product_backlog

  def to_s
    name
  end

  def is_product_backlog?
    self.is_product_backlog
  end

  def pbis
    issues.all(conditions: {tracker_id: Scrum::Setting.pbi_tracker_ids},
               order: "position ASC").select{|issue| issue.visible?}
  end

  def story_points
    pbis.collect{|pbi| pbi.story_points.to_f}.compact.sum
  end

  def remained_story_points(date, story_points, closed_stories)
    closedPoints = closed_stories.select { |pbi| pbi.closed_on.getlocal.to_date <= date }.collect { |pbi| pbi.story_points.to_f }.compact.sum
    story_points - closedPoints
  end

  def closed_stories
    pbis.select{|pbi| pbi.status == IssueStatus.where(:is_closed => true).first}
  end

  def tasks
    issues.all(conditions: {tracker_id: Scrum::Setting.task_tracker_ids}).select{|issue| issue.visible?}
  end

  def estimated_hours
    tasks.collect{|task| task.estimated_hours}.compact.sum
  end

  def self.fields_for_order_statement(table = nil)
    table ||= table_name
    ["(CASE WHEN #{table}.end_date IS NULL THEN 1 ELSE 0 END)",
     "#{table}.end_date",
     "#{table}.name",
     "#{table}.id"]
  end

  scope :sorted, order(fields_for_order_statement)

private

  def update_project_product_backlog
    if is_product_backlog?
      project.product_backlog = nil
      project.save!
    end
  end

end

app/controllers/sprints_controller.rb
class SprintsController < ApplicationController

  menu_item :scrum
  model_object Sprint

  before_filter :find_model_object,
                :only => [:show, :edit, :update, :destroy, :edit_effort, :update_effort, :burndown]
  before_filter :find_project_from_association,
                :only => [:show, :edit, :update, :destroy, :edit_effort, :update_effort, :burndown]
  before_filter :find_project_by_project_id,
                :only => [:index, :new, :create, :change_task_status, :burndown_index]
  before_filter :authorize

  helper :custom_fields
  helper :scrum
  helper :timelog

  def index
    redirect_to sprint_path(@project.last_sprint)
  rescue
    render_404
  end

  def show
    redirect_to project_product_backlog_index_path(@project) if @sprint.is_product_backlog?
  end

  def new
    @sprint = Sprint.new(:project => @project)
    if params[:create_product_backlog]
      @sprint.name = l(:label_product_backlog)
      @sprint.start_date = @sprint.end_date = Date.today
    end
  end

  def create
    raise "Product backlog is already set" if params[:create_product_backlog] and
                                              !(@project.product_backlog.nil?)
    @sprint = Sprint.new(params[:sprint].merge(:user => User.current,
                                               :project => @project,
                                               :is_product_backlog => (!(params[:create_product_backlog].nil?))))
    if request.post? and @sprint.save
      if params[:create_product_backlog]
        @project.product_backlog = @sprint
        raise "Fail to update project with product backlog" unless @project.save!
      end
      flash[:notice] = l(:notice_successful_create)
      redirect_to settings_project_path(@project, :tab => "sprints")
    end
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def edit
  end

  def update
    if @sprint.update_attributes(params[:sprint])
      flash[:notice] = l(:notice_successful_update)
      redirect_to settings_project_path(@project, :tab => "sprints")
    end
  end

  def destroy
    if @sprint.issues.any?
      flash[:error] = l(:notice_sprint_has_issues)
    else
      @sprint.destroy
    end
  rescue
    flash[:error] = l(:notice_unable_delete_sprint)
  ensure
    redirect_to settings_project_path(@project, :tab => "sprints")
  end

  def change_task_status
    task = Issue.find(params[:task].match(/^task_(\d+)$/)[1].to_i)
    task.init_journal(User.current)
    task.status = IssueStatus.find(params[:status].to_i)
    task.save!
    render :nothing => true
  end

  def edit_effort
  end

  def update_effort
    params[:user].each_pair do |user_id, days|
      user_id = user_id.to_i
      days.each_pair do |day, effort|
        day = day.to_i
        date = @sprint.start_date + day.to_i
        sprint_effort = SprintEffort.find(:first,
                                          :conditions => {:sprint_id => @sprint.id,
                                                          :user_id => user_id,
                                                          :date => date})
        if sprint_effort.nil?
          unless effort.blank?
            sprint_effort = SprintEffort.new(:sprint_id => @sprint.id,
                                             :user_id => user_id,
                                             :date => @sprint.start_date + day,
                                             :effort => effort)
          end
        elsif effort.blank?
          sprint_effort.destroy
          sprint_effort = nil
        else
          sprint_effort.effort = effort
        end
        sprint_effort.save! unless sprint_effort.nil?
      end
    end
    flash[:notice] = l(:notice_successful_update)
    redirect_to settings_project_path(@project, :tab => "sprints")
  end

  def burndown_index
    redirect_to burndown_sprint_path(@project.last_sprint)
  rescue
    render_404
  end

  def burndown
    @data = []
    closed_stories = @sprint.closed_stories
    story_points = @sprint.story_points
    ((@sprint.start_date)..(@sprint.end_date)).each do |date|
        if date <= Date.today
          remained_story_points = @sprint.remained_story_points(date, story_points, closed_stories)
        end
        date_label = "#{I18n.l(date, :format => :scrum_day)} #{date.day}"
        @data << {day: date,
                  axis_label: date_label,
                  estimated_effort: 0,
                  estimated_effort_tooltip: date_label,

                  pending_effort: remained_story_points,
                  pending_effort_tooltip: l(:label_story_points_tooltip,
                                            date: date_label,
                                            story_points: remained_story_points)}
    end
  end

end

app/views/sprints/_burndown.js.erb
<%= javascript_tag do %>
	// Create the tooltip DOM element.
	var toolTip = document.createElement("div"),
		leftOffset = -(~~$("html").css("padding-left").replace("px", "") + ~~$("body").css("margin-left").replace("px", "")),
		topOffset = -32;
	toolTip.className = "graphic-tooltip";
	document.body.appendChild(toolTip);
	// Chart data.
	var data = {
		// Horizontal set of values (ordinal), vertical values (linear).
		"xScale": "ordinal",
		"yScale": "linear",
		"main": [
			{
				// Estimated effort serie.
				"className": ".estimated-effort",
				"data": [
				<%- data.each_with_index do |value, i| -%>
					{
						"x": <%= i %>,
						"y": 0,
						"axis_label": "<%= value[:axis_label] %>",
						"tooltip": "<%= value[:estimated_effort_tooltip] %>"
					},
				<%- end -%>
				]
			},
			{
				// Pending effort serie.
				"className": ".pending-effort",
				"data": [
				<%- data.each_with_index do |value, i| -%>
					<%- unless value[:pending_effort].nil? -%>
					{
						"x": <%= i %>,
						"y": <%= value[:pending_effort] %>,
						"axis_label": "<%= value[:axis_label] %>",
						"tooltip": "<%= value[:pending_effort_tooltip] %>"
					},
					<%- end -%>
				<%- end -%>
				]
			}
		]
	};
	// Chart options.
	var options = {
		// Use data label as horizontal axis labels.
		"tickFormatX": function (x) { return data["main"][0]["data"][x]["axis_label"]; },
		// Render a tooltip when mouse goes over the values.
		"mouseover": function (d, i) {
			var pos = $(this).offset();
			$(toolTip).text(d.tooltip)
			.css({top: topOffset + pos.top, left: pos.left + leftOffset})
			.show();
		},
		// Hide the tooltip when mouse exists the values.
		"mouseout": function (x) {
			$(toolTip).hide();
		}
	};
	// Generate the chart.
	new xChart("line-dotted", data, "#burndown-chart", options);
<% end %>

app/views/sprints/_form.html.erb
<%= back_url_hidden_field_tag %>
<%= error_messages_for "sprint" %>

<div class="box tabular">
  <p><%= f.text_field :name, size: 60, required: true %></p>
  <p><%= f.text_field :description, :size => 60 %></p>
  <p>
    <%= f.text_field :start_date, size: 10, required: true %>
    <%= calendar_for "sprint_start_date" %>
  </p>
  <p>
    <%= f.text_field :end_date, size: 10, required: true %>
    <%= calendar_for "sprint_end_date" %>
  </p>
</div>

app/views/sprints/burndown.html.erb
<%= render partial: "common/scrum_menu" %>

<h2>
  <%= l(:label_sprint_burndown_chart) %>
</h2>

<%= render partial: "post_its/sprint_board/head",
           locals: {project: @project,
                    sprint: @sprint,
                    path: method(:burndown_sprint_path)} %>

<% content_for :header_tags do %>
  <%= javascript_include_tag "d3.min.js", :plugin => "scrum" %>
  <%= javascript_include_tag "xcharts.min.js", :plugin => "scrum" %>
  <%= stylesheet_link_tag "xcharts.min.css", :plugin => "scrum" %>
<% end %>

<div style="right: 10px; position: absolute;">
  <svg height="80" width="300" class="xchart">
    <g class="line color1"><path class="line" stroke-width="10" d="M5 35 H70" /></g>
    <g class="axis"><text x="80" y="38"><%= l(:label_story_point_plural) %></text></g>
  </svg>
</div>
<figure style="left-margin: auto; right-margin:auto; width: 90%; height: 500px;" id="burndown-chart" />

<%= render partial: "sprints/burndown", formats: [:js], locals: {data: @data} %>

<%= render partial: "common/scrum_footer" %>

app/views/sprints/edit.html.erb
<h2><%= l(:label_sprint) %></h2>

<%= labelled_form_for @sprint do |f| %>
  <%= render partial: "sprints/form", locals: {f: f} %>
  <%= submit_tag l(:button_save) %>
<% end %>

<%= render partial: "common/scrum_footer" %>

app/views/sprints/edit_effort.html.erb
<h2><%= l(:label_edit_effort) %></h2>

<div class="box tabular">
  <p>
    <label><%= l(:label_sprint) %>:</label>
    <%= @sprint.name %>
  </p>
  <p>
    <label><%= l(:field_start_date) %>:</label>
    <%= format_date @sprint.start_date %>
  </p>
  <p>
    <label><%= l(:field_end_date) %>:</label>
    <%= format_date @sprint.end_date %>
  </p>
  <%- if !(@sprint.description.blank?) -%>
    <p>
      <label><%= l(:field_description) %>:</label>
      <%= h @sprint.description %>
    </p>
  <%- end -%>
</div>

<%- if @project.sprints_and_product_backlog.empty? -%>
  <p class="nodata"><%= l(:label_no_data) %></p>
<%- else -%>
  <%= labelled_form_for @sprint, url: update_effort_sprint_path(@sprint) do |f| %>
    <%- days = (@sprint.end_date - @sprint.start_date).to_i + 1 -%>
    <table class="list" style="overflow: auto;">
      <thead>
        <tr>
          <th><%= l(:field_user) %></th>
          <%- ((@sprint.start_date)..(@sprint.end_date)).each do |date| -%>
            <th><%= I18n.l(date, format: :scrum_day) %><br /><%= date.day %></th>
          <%- end -%>
        </tr>
      </thead>
      <tbody>
        <%- @project.members.each do |member| -%>
          <tr class="<%= cycle 'odd', 'even' %>">
            <td><%= link_to_user(member.user) %></td>
            <%- days.times do |day| -%>
              <td align="center">
                <%- effort = @sprint.efforts.find_by_user_id_and_date(member.user.id,
                                                                      @sprint.start_date + day) -%>
                <%= text_field_tag "user[#{member.user.id}][#{day}]",
                                   effort.nil? ? nil : effort.effort,
                                   size: 2 %>
              </td>
            <%- end -%>
          </tr>
        <% end; reset_cycle %>
      <tbody>
    </table>
    <%= submit_tag l(:button_save) %>
  <% end %>
<%- end -%>

<%= render partial: "common/scrum_footer" %>

app/views/sprints/new.html.erb
<h2><%= l(@sprint.is_product_backlog? ? :label_sprint_new : :label_product_backlog_new) %></h2>

<%= labelled_form_for @sprint, url: project_sprints_path(@project) do |f| %>
  <%= render partial: "sprints/form", locals: {f: f} %>
  <%= hidden_field_tag :create_product_backlog, true if params[:create_product_backlog] %>
  <%= submit_tag l(:button_create) %>
<% end %>

<%= render partial: "common/scrum_footer" %>

app/views/sprints/show.html.erb
<%= render partial: "common/scrum_menu" %>

<h2>
  <%= l(:label_sprint_board) %>
</h2>

<%= render partial: "post_its/sprint_board/head",
           locals: {project: @project, sprint: @sprint, path: method(:sprint_path)} %>

<%- if @sprint.pbis.empty? -%>
  <p class="nodata"><%= l(:label_no_data) %></p>
<%- else -%>
  <table id="sprint_board" class="sprint-board">
    <tr class="sprint-board">
      <%- task_statuses = IssueStatus.task_statuses
          task_statuses.each do |status| -%>
        <th class="sprint-board"><%= status.name %></th>
      <%- end -%>
    </tr>
    <%- @sprint.pbis.each do |pbi| -%>
      <%= render partial: "post_its/sprint_board/pbi_row",
                 locals: {project: @project, pbi: pbi, task_statuses: task_statuses} %>
    <%- end -%>
  </table>
<%- end -%>

<%- if User.current.allowed_to?(:add_issues, @project) -%>
  <div>
    <%- Tracker.pbi_trackers.each do |tracker| -%>
      <%= link_to tracker.name, new_pbi_path(@sprint, tracker), remote: true,
                  method: "GET", class: "icon icon-add" %>
    <%- end -%>
  </div>
<%- end -%>

<%= render partial: "common/scrum_footer" %>